title: ""
description: ""

theme: jekyll-theme-minimal

# Custom navigation links
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/SilviaMiramontes_CV.pdf
