title: " "  # removes big name
description: ""  # removes subtitle
theme: jekyll-theme-minimal

show_downloads: false  # hides GitHub profile link

navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/SilviaMiramontes_CV.pdf
