title: Silvia Miramontes
description: Clinical Data Scientist | RWE • ML • EHR

theme: jekyll-theme-minimal

# Custom navigation links
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/SilviaMiramontes_CV.pdf
